# Generated by Django 2.1.7 on 2019-05-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('preciofinal', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_cliente', models.CharField(max_length=32)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(null=True)),
                ('metodo_pago', models.CharField(max_length=32)),
                ('envio_dian', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=1000)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.Factura'),
        ),
    ]
