# Generated by Django 2.1.7 on 2019-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20190522_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='preciofinal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
