# Generated by Django 2.1.7 on 2019-05-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_auto_20190522_0133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('id_factura', 'id_producto')},
        ),
    ]
